# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'STAGE/test_Designer.ui'
#
# Created by: PyQt5 UI code generator 5.10.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_principale_IHM(object):
    def setupUi(self, principale_IHM):
        principale_IHM.setObjectName("principale_IHM")
        principale_IHM.resize(893, 993)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(principale_IHM.sizePolicy().hasHeightForWidth())
        principale_IHM.setSizePolicy(sizePolicy)
        principale_IHM.setMinimumSize(QtCore.QSize(815, 993))
        principale_IHM.setMaximumSize(QtCore.QSize(893, 993))
        self.centralwidget = QtWidgets.QWidget(principale_IHM)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setMinimumSize(QtCore.QSize(899, 668))
        self.tabWidget.setMaximumSize(QtCore.QSize(799, 968))
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.tableWidget = QtWidgets.QTableWidget(self.tab)
        self.tableWidget.setGeometry(QtCore.QRect(440, 210, 201, 451))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tableWidget.sizePolicy().hasHeightForWidth())
        self.tableWidget.setSizePolicy(sizePolicy)
        self.tableWidget.setMaximumSize(QtCore.QSize(300, 16777215))
        self.tableWidget.setShowGrid(False)
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(2)
        self.tableWidget.setRowCount(7)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(6, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(1, item)
        self.tableWidget.horizontalHeader().setVisible(True)
        self.tableWidget.verticalHeader().setVisible(False)
        self.groupBox = QtWidgets.QGroupBox(self.tab)
        self.groupBox.setEnabled(True)
        self.groupBox.setGeometry(QtCore.QRect(300, 30, 521, 153))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(3)
        sizePolicy.setVerticalStretch(2)
        sizePolicy.setHeightForWidth(self.groupBox.sizePolicy().hasHeightForWidth())
        self.groupBox.setSizePolicy(sizePolicy)
        self.groupBox.setMinimumSize(QtCore.QSize(200, 0))
        self.groupBox.setObjectName("groupBox")
        self.gridLayout = QtWidgets.QGridLayout(self.groupBox)
        self.gridLayout.setContentsMargins(-1, -1, 30, -1)
        self.gridLayout.setHorizontalSpacing(60)
        self.gridLayout.setVerticalSpacing(24)
        self.gridLayout.setObjectName("gridLayout")
        self.label__txt_file = QtWidgets.QLabel(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.label__txt_file.sizePolicy().hasHeightForWidth())
        self.label__txt_file.setSizePolicy(sizePolicy)
        self.label__txt_file.setObjectName("label__txt_file")
        self.gridLayout.addWidget(self.label__txt_file, 0, 0, 1, 1)
        self.label__txt_file_2 = QtWidgets.QLabel(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.label__txt_file_2.sizePolicy().hasHeightForWidth())
        self.label__txt_file_2.setSizePolicy(sizePolicy)
        self.label__txt_file_2.setObjectName("label__txt_file_2")
        self.gridLayout.addWidget(self.label__txt_file_2, 1, 0, 1, 1)
        self.label = QtWidgets.QLabel(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 2, 1, 1)
        self.pushButton_4 = QtWidgets.QPushButton(self.groupBox)
        self.pushButton_4.setObjectName("pushButton_4")
        self.gridLayout.addWidget(self.pushButton_4, 2, 1, 1, 1)
        self.comboBox = QtWidgets.QComboBox(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.comboBox.sizePolicy().hasHeightForWidth())
        self.comboBox.setSizePolicy(sizePolicy)
        self.comboBox.setMinimumSize(QtCore.QSize(200, 0))
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.gridLayout.addWidget(self.comboBox, 1, 2, 1, 1)
        self.label.raise_()
        self.label__txt_file_2.raise_()
        self.comboBox.raise_()
        self.label__txt_file.raise_()
        self.pushButton_4.raise_()
        self.treeWidget = QtWidgets.QTreeWidget(self.tab)
        self.treeWidget.setGeometry(QtCore.QRect(30, 40, 218, 621))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.treeWidget.sizePolicy().hasHeightForWidth())
        self.treeWidget.setSizePolicy(sizePolicy)
        self.treeWidget.setMinimumSize(QtCore.QSize(118, 485))
        self.treeWidget.setMaximumSize(QtCore.QSize(218, 16777215))
        self.treeWidget.setObjectName("treeWidget")
        item_0 = QtWidgets.QTreeWidgetItem(self.treeWidget)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_2 = QtWidgets.QTreeWidgetItem(item_1)
        item_3 = QtWidgets.QTreeWidgetItem(item_2)
        self.line = QtWidgets.QFrame(self.tab)
        self.line.setGeometry(QtCore.QRect(660, 220, 20, 441))
        self.line.setFrameShape(QtWidgets.QFrame.VLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.pushButton = QtWidgets.QPushButton(self.tab)
        self.pushButton.setGeometry(QtCore.QRect(680, 620, 113, 32))
        self.pushButton.setAutoDefault(False)
        self.pushButton.setDefault(True)
        self.pushButton.setFlat(False)
        self.pushButton.setObjectName("pushButton")
        self.pushButton_2 = QtWidgets.QPushButton(self.tab)
        self.pushButton_2.setGeometry(QtCore.QRect(680, 590, 113, 32))
        self.pushButton_2.setObjectName("pushButton_2")
        self.tabWidget.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.groupBox_3 = QtWidgets.QGroupBox(self.tab_2)
        self.groupBox_3.setGeometry(QtCore.QRect(100, 40, 681, 731))
        self.groupBox_3.setTitle("")
        self.groupBox_3.setObjectName("groupBox_3")
        self.layoutWidget_2 = QtWidgets.QWidget(self.groupBox_3)
        self.layoutWidget_2.setGeometry(QtCore.QRect(50, 20, 531, 198))
        self.layoutWidget_2.setObjectName("layoutWidget_2")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout(self.layoutWidget_2)
        self.horizontalLayout_6.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.label_5 = QtWidgets.QLabel(self.layoutWidget_2)
        self.label_5.setObjectName("label_5")
        self.horizontalLayout_6.addWidget(self.label_5)
        self.comboBox_2 = QtWidgets.QComboBox(self.layoutWidget_2)
        self.comboBox_2.setObjectName("comboBox_2")
        self.horizontalLayout_6.addWidget(self.comboBox_2)
        self.label_8 = QtWidgets.QLabel(self.layoutWidget_2)
        self.label_8.setObjectName("label_8")
        self.horizontalLayout_6.addWidget(self.label_8)
        spacerItem = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem)
        self.tableWidget_2 = QtWidgets.QTableWidget(self.layoutWidget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tableWidget_2.sizePolicy().hasHeightForWidth())
        self.tableWidget_2.setSizePolicy(sizePolicy)
        self.tableWidget_2.setMaximumSize(QtCore.QSize(200, 16777215))
        self.tableWidget_2.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAsNeeded)
        self.tableWidget_2.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.tableWidget_2.setAutoScroll(False)
        self.tableWidget_2.setShowGrid(False)
        self.tableWidget_2.setCornerButtonEnabled(True)
        self.tableWidget_2.setObjectName("tableWidget_2")
        self.tableWidget_2.setColumnCount(2)
        self.tableWidget_2.setRowCount(9)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setVerticalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setVerticalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setVerticalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setVerticalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setVerticalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setVerticalHeaderItem(6, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setVerticalHeaderItem(7, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setVerticalHeaderItem(8, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setItem(0, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setItem(0, 1, item)
        self.tableWidget_2.verticalHeader().setVisible(False)
        self.horizontalLayout_6.addWidget(self.tableWidget_2)
        self.groupBox_4 = QtWidgets.QGroupBox(self.groupBox_3)
        self.groupBox_4.setGeometry(QtCore.QRect(50, 220, 531, 161))
        self.groupBox_4.setObjectName("groupBox_4")
        self.label_24 = QtWidgets.QLabel(self.groupBox_4)
        self.label_24.setGeometry(QtCore.QRect(10, 30, 341, 16))
        self.label_24.setObjectName("label_24")
        self.pushButton_3 = QtWidgets.QPushButton(self.groupBox_4)
        self.pushButton_3.setGeometry(QtCore.QRect(450, 120, 71, 32))
        self.pushButton_3.setObjectName("pushButton_3")
        self.line_5 = QtWidgets.QFrame(self.groupBox_4)
        self.line_5.setGeometry(QtCore.QRect(17, 100, 501, 20))
        self.line_5.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_5.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_5.setObjectName("line_5")
        self.widget = QtWidgets.QWidget(self.groupBox_4)
        self.widget.setGeometry(QtCore.QRect(10, 48, 291, 56))
        self.widget.setObjectName("widget")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout(self.widget)
        self.horizontalLayout_7.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.comboBox_3 = QtWidgets.QComboBox(self.widget)
        self.comboBox_3.setObjectName("comboBox_3")
        self.horizontalLayout_7.addWidget(self.comboBox_3)
        self.label_25 = QtWidgets.QLabel(self.widget)
        self.label_25.setObjectName("label_25")
        self.horizontalLayout_7.addWidget(self.label_25)
        self.label_26 = QtWidgets.QLabel(self.widget)
        self.label_26.setObjectName("label_26")
        self.horizontalLayout_7.addWidget(self.label_26)
        self.dial_9 = QtWidgets.QDial(self.widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.dial_9.sizePolicy().hasHeightForWidth())
        self.dial_9.setSizePolicy(sizePolicy)
        self.dial_9.setMaximumSize(QtCore.QSize(50, 50))
        self.dial_9.setObjectName("dial_9")
        self.horizontalLayout_7.addWidget(self.dial_9)
        self.graphicsView = QtWidgets.QGraphicsView(self.groupBox_3)
        self.graphicsView.setGeometry(QtCore.QRect(220, 390, 351, 241))
        self.graphicsView.setObjectName("graphicsView")
        self.pushButton_5 = QtWidgets.QPushButton(self.groupBox_3)
        self.pushButton_5.setGeometry(QtCore.QRect(80, 500, 121, 32))
        self.pushButton_5.setObjectName("pushButton_5")
        self.tabWidget.addTab(self.tab_2, "")
        self.Influencers = QtWidgets.QWidget()
        self.Influencers.setObjectName("Influencers")
        self.label_3 = QtWidgets.QLabel(self.Influencers)
        self.label_3.setGeometry(QtCore.QRect(80, 40, 60, 16))
        self.label_3.setText("")
        self.label_3.setObjectName("label_3")
        self.groupBox_2 = QtWidgets.QGroupBox(self.Influencers)
        self.groupBox_2.setGeometry(QtCore.QRect(10, 20, 801, 841))
        self.groupBox_2.setMinimumSize(QtCore.QSize(34, 820))
        self.groupBox_2.setCheckable(True)
        self.groupBox_2.setObjectName("groupBox_2")
        self.label_4 = QtWidgets.QLabel(self.groupBox_2)
        self.label_4.setGeometry(QtCore.QRect(20, 30, 241, 16))
        self.label_4.setObjectName("label_4")
        self.label_12 = QtWidgets.QLabel(self.groupBox_2)
        self.label_12.setGeometry(QtCore.QRect(360, 60, 361, 51))
        self.label_12.setWordWrap(True)
        self.label_12.setObjectName("label_12")
        self.line_2 = QtWidgets.QFrame(self.groupBox_2)
        self.line_2.setGeometry(QtCore.QRect(390, 190, 20, 551))
        self.line_2.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.label_6 = QtWidgets.QLabel(self.groupBox_2)
        self.label_6.setGeometry(QtCore.QRect(20, 130, 60, 16))
        self.label_6.setObjectName("label_6")
        self.label_7 = QtWidgets.QLabel(self.groupBox_2)
        self.label_7.setGeometry(QtCore.QRect(430, 130, 60, 16))
        self.label_7.setObjectName("label_7")
        self.line_3 = QtWidgets.QFrame(self.groupBox_2)
        self.line_3.setGeometry(QtCore.QRect(50, 350, 291, 20))
        self.line_3.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_3.setObjectName("line_3")
        self.gridLayoutWidget = QtWidgets.QWidget(self.groupBox_2)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(10, 150, 371, 201))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout_2.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.label_13 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_13.setObjectName("label_13")
        self.gridLayout_2.addWidget(self.label_13, 1, 3, 1, 1, QtCore.Qt.AlignHCenter)
        self.label_10 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_10.setObjectName("label_10")
        self.gridLayout_2.addWidget(self.label_10, 0, 3, 1, 1, QtCore.Qt.AlignHCenter)
        self.checkBox = QtWidgets.QCheckBox(self.gridLayoutWidget)
        self.checkBox.setObjectName("checkBox")
        self.gridLayout_2.addWidget(self.checkBox, 0, 0, 1, 1)
        self.dial_3 = QtWidgets.QDial(self.gridLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.dial_3.sizePolicy().hasHeightForWidth())
        self.dial_3.setSizePolicy(sizePolicy)
        self.dial_3.setMaximumSize(QtCore.QSize(50, 50))
        self.dial_3.setObjectName("dial_3")
        self.gridLayout_2.addWidget(self.dial_3, 1, 4, 1, 1)
        self.label_9 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_9.setObjectName("label_9")
        self.gridLayout_2.addWidget(self.label_9, 0, 2, 1, 1)
        self.dial_2 = QtWidgets.QDial(self.gridLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.dial_2.sizePolicy().hasHeightForWidth())
        self.dial_2.setSizePolicy(sizePolicy)
        self.dial_2.setMaximumSize(QtCore.QSize(50, 50))
        self.dial_2.setObjectName("dial_2")
        self.gridLayout_2.addWidget(self.dial_2, 0, 4, 1, 1)
        self.label_11 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_11.setObjectName("label_11")
        self.gridLayout_2.addWidget(self.label_11, 1, 2, 1, 1)
        self.checkBox_2 = QtWidgets.QCheckBox(self.gridLayoutWidget)
        self.checkBox_2.setObjectName("checkBox_2")
        self.gridLayout_2.addWidget(self.checkBox_2, 1, 0, 1, 1)
        self.frame = QtWidgets.QFrame(self.gridLayoutWidget)
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.verticalLayout_10 = QtWidgets.QVBoxLayout(self.frame)
        self.verticalLayout_10.setContentsMargins(6, 0, 0, 0)
        self.verticalLayout_10.setObjectName("verticalLayout_10")
        self.spinBox = QtWidgets.QSpinBox(self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.spinBox.sizePolicy().hasHeightForWidth())
        self.spinBox.setSizePolicy(sizePolicy)
        self.spinBox.setObjectName("spinBox")
        self.verticalLayout_10.addWidget(self.spinBox)
        self.radioButton = QtWidgets.QRadioButton(self.frame)
        self.radioButton.setObjectName("radioButton")
        self.verticalLayout_10.addWidget(self.radioButton)
        self.gridLayout_2.addWidget(self.frame, 0, 1, 1, 1)
        self.frame_2 = QtWidgets.QFrame(self.gridLayoutWidget)
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.verticalLayout_11 = QtWidgets.QVBoxLayout(self.frame_2)
        self.verticalLayout_11.setContentsMargins(6, 0, 0, 0)
        self.verticalLayout_11.setObjectName("verticalLayout_11")
        self.spinBox_2 = QtWidgets.QSpinBox(self.frame_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.spinBox_2.sizePolicy().hasHeightForWidth())
        self.spinBox_2.setSizePolicy(sizePolicy)
        self.spinBox_2.setObjectName("spinBox_2")
        self.verticalLayout_11.addWidget(self.spinBox_2)
        self.radioButton_2 = QtWidgets.QRadioButton(self.frame_2)
        self.radioButton_2.setObjectName("radioButton_2")
        self.verticalLayout_11.addWidget(self.radioButton_2)
        self.gridLayout_2.addWidget(self.frame_2, 1, 1, 1, 1)
        self.checkBox_3 = QtWidgets.QCheckBox(self.gridLayoutWidget)
        self.checkBox_3.setObjectName("checkBox_3")
        self.gridLayout_2.addWidget(self.checkBox_3, 2, 0, 1, 1)
        self.frame_3 = QtWidgets.QFrame(self.gridLayoutWidget)
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.verticalLayout_12 = QtWidgets.QVBoxLayout(self.frame_3)
        self.verticalLayout_12.setContentsMargins(6, 0, 0, 0)
        self.verticalLayout_12.setObjectName("verticalLayout_12")
        self.spinBox_3 = QtWidgets.QSpinBox(self.frame_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.spinBox_3.sizePolicy().hasHeightForWidth())
        self.spinBox_3.setSizePolicy(sizePolicy)
        self.spinBox_3.setObjectName("spinBox_3")
        self.verticalLayout_12.addWidget(self.spinBox_3)
        self.radioButton_3 = QtWidgets.QRadioButton(self.frame_3)
        self.radioButton_3.setObjectName("radioButton_3")
        self.verticalLayout_12.addWidget(self.radioButton_3)
        self.gridLayout_2.addWidget(self.frame_3, 2, 1, 1, 1)
        self.label_14 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_14.setObjectName("label_14")
        self.gridLayout_2.addWidget(self.label_14, 2, 2, 1, 1)
        self.label_15 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_15.setObjectName("label_15")
        self.gridLayout_2.addWidget(self.label_15, 2, 3, 1, 1, QtCore.Qt.AlignHCenter)
        self.dial_4 = QtWidgets.QDial(self.gridLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.dial_4.sizePolicy().hasHeightForWidth())
        self.dial_4.setSizePolicy(sizePolicy)
        self.dial_4.setMaximumSize(QtCore.QSize(50, 50))
        self.dial_4.setObjectName("dial_4")
        self.gridLayout_2.addWidget(self.dial_4, 2, 4, 1, 1)
        self.gridLayoutWidget_2 = QtWidgets.QWidget(self.groupBox_2)
        self.gridLayoutWidget_2.setGeometry(QtCore.QRect(10, 370, 371, 201))
        self.gridLayoutWidget_2.setObjectName("gridLayoutWidget_2")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.gridLayoutWidget_2)
        self.gridLayout_3.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.label_16 = QtWidgets.QLabel(self.gridLayoutWidget_2)
        self.label_16.setObjectName("label_16")
        self.gridLayout_3.addWidget(self.label_16, 1, 3, 1, 1, QtCore.Qt.AlignHCenter)
        self.label_17 = QtWidgets.QLabel(self.gridLayoutWidget_2)
        self.label_17.setObjectName("label_17")
        self.gridLayout_3.addWidget(self.label_17, 0, 3, 1, 1, QtCore.Qt.AlignHCenter)
        self.checkBox_4 = QtWidgets.QCheckBox(self.gridLayoutWidget_2)
        self.checkBox_4.setObjectName("checkBox_4")
        self.gridLayout_3.addWidget(self.checkBox_4, 0, 0, 1, 1)
        self.dial_5 = QtWidgets.QDial(self.gridLayoutWidget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.dial_5.sizePolicy().hasHeightForWidth())
        self.dial_5.setSizePolicy(sizePolicy)
        self.dial_5.setMaximumSize(QtCore.QSize(50, 50))
        self.dial_5.setObjectName("dial_5")
        self.gridLayout_3.addWidget(self.dial_5, 1, 4, 1, 1)
        self.label_18 = QtWidgets.QLabel(self.gridLayoutWidget_2)
        self.label_18.setObjectName("label_18")
        self.gridLayout_3.addWidget(self.label_18, 0, 2, 1, 1)
        self.dial_6 = QtWidgets.QDial(self.gridLayoutWidget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.dial_6.sizePolicy().hasHeightForWidth())
        self.dial_6.setSizePolicy(sizePolicy)
        self.dial_6.setMaximumSize(QtCore.QSize(50, 50))
        self.dial_6.setObjectName("dial_6")
        self.gridLayout_3.addWidget(self.dial_6, 0, 4, 1, 1)
        self.label_19 = QtWidgets.QLabel(self.gridLayoutWidget_2)
        self.label_19.setObjectName("label_19")
        self.gridLayout_3.addWidget(self.label_19, 1, 2, 1, 1)
        self.checkBox_5 = QtWidgets.QCheckBox(self.gridLayoutWidget_2)
        self.checkBox_5.setObjectName("checkBox_5")
        self.gridLayout_3.addWidget(self.checkBox_5, 1, 0, 1, 1)
        self.frame_4 = QtWidgets.QFrame(self.gridLayoutWidget_2)
        self.frame_4.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_4.setObjectName("frame_4")
        self.verticalLayout_13 = QtWidgets.QVBoxLayout(self.frame_4)
        self.verticalLayout_13.setContentsMargins(6, 0, 0, 0)
        self.verticalLayout_13.setObjectName("verticalLayout_13")
        self.spinBox_4 = QtWidgets.QSpinBox(self.frame_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.spinBox_4.sizePolicy().hasHeightForWidth())
        self.spinBox_4.setSizePolicy(sizePolicy)
        self.spinBox_4.setObjectName("spinBox_4")
        self.verticalLayout_13.addWidget(self.spinBox_4)
        self.radioButton_4 = QtWidgets.QRadioButton(self.frame_4)
        self.radioButton_4.setObjectName("radioButton_4")
        self.verticalLayout_13.addWidget(self.radioButton_4)
        self.gridLayout_3.addWidget(self.frame_4, 0, 1, 1, 1)
        self.frame_5 = QtWidgets.QFrame(self.gridLayoutWidget_2)
        self.frame_5.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_5.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_5.setObjectName("frame_5")
        self.verticalLayout_14 = QtWidgets.QVBoxLayout(self.frame_5)
        self.verticalLayout_14.setContentsMargins(6, 0, 0, 0)
        self.verticalLayout_14.setObjectName("verticalLayout_14")
        self.spinBox_5 = QtWidgets.QSpinBox(self.frame_5)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.spinBox_5.sizePolicy().hasHeightForWidth())
        self.spinBox_5.setSizePolicy(sizePolicy)
        self.spinBox_5.setObjectName("spinBox_5")
        self.verticalLayout_14.addWidget(self.spinBox_5)
        self.radioButton_5 = QtWidgets.QRadioButton(self.frame_5)
        self.radioButton_5.setObjectName("radioButton_5")
        self.verticalLayout_14.addWidget(self.radioButton_5)
        self.gridLayout_3.addWidget(self.frame_5, 1, 1, 1, 1)
        self.checkBox_6 = QtWidgets.QCheckBox(self.gridLayoutWidget_2)
        self.checkBox_6.setObjectName("checkBox_6")
        self.gridLayout_3.addWidget(self.checkBox_6, 2, 0, 1, 1)
        self.frame_6 = QtWidgets.QFrame(self.gridLayoutWidget_2)
        self.frame_6.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_6.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_6.setObjectName("frame_6")
        self.verticalLayout_15 = QtWidgets.QVBoxLayout(self.frame_6)
        self.verticalLayout_15.setContentsMargins(6, 0, 0, 0)
        self.verticalLayout_15.setObjectName("verticalLayout_15")
        self.spinBox_6 = QtWidgets.QSpinBox(self.frame_6)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.spinBox_6.sizePolicy().hasHeightForWidth())
        self.spinBox_6.setSizePolicy(sizePolicy)
        self.spinBox_6.setObjectName("spinBox_6")
        self.verticalLayout_15.addWidget(self.spinBox_6)
        self.radioButton_6 = QtWidgets.QRadioButton(self.frame_6)
        self.radioButton_6.setObjectName("radioButton_6")
        self.verticalLayout_15.addWidget(self.radioButton_6)
        self.gridLayout_3.addWidget(self.frame_6, 2, 1, 1, 1)
        self.label_20 = QtWidgets.QLabel(self.gridLayoutWidget_2)
        self.label_20.setObjectName("label_20")
        self.gridLayout_3.addWidget(self.label_20, 2, 2, 1, 1)
        self.label_21 = QtWidgets.QLabel(self.gridLayoutWidget_2)
        self.label_21.setObjectName("label_21")
        self.gridLayout_3.addWidget(self.label_21, 2, 3, 1, 1, QtCore.Qt.AlignRight)
        self.dial_7 = QtWidgets.QDial(self.gridLayoutWidget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.dial_7.sizePolicy().hasHeightForWidth())
        self.dial_7.setSizePolicy(sizePolicy)
        self.dial_7.setMaximumSize(QtCore.QSize(50, 50))
        self.dial_7.setObjectName("dial_7")
        self.gridLayout_3.addWidget(self.dial_7, 2, 4, 1, 1)
        self.line_4 = QtWidgets.QFrame(self.groupBox_2)
        self.line_4.setGeometry(QtCore.QRect(10, 110, 741, 16))
        self.line_4.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_4.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_4.setObjectName("line_4")
        self.gridLayoutWidget_5 = QtWidgets.QWidget(self.groupBox_2)
        self.gridLayoutWidget_5.setGeometry(QtCore.QRect(10, 590, 371, 201))
        self.gridLayoutWidget_5.setObjectName("gridLayoutWidget_5")
        self.gridLayout_6 = QtWidgets.QGridLayout(self.gridLayoutWidget_5)
        self.gridLayout_6.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.label_41 = QtWidgets.QLabel(self.gridLayoutWidget_5)
        self.label_41.setObjectName("label_41")
        self.gridLayout_6.addWidget(self.label_41, 1, 3, 1, 1, QtCore.Qt.AlignHCenter)
        self.label_42 = QtWidgets.QLabel(self.gridLayoutWidget_5)
        self.label_42.setObjectName("label_42")
        self.gridLayout_6.addWidget(self.label_42, 0, 3, 1, 1, QtCore.Qt.AlignHCenter)
        self.checkBox_15 = QtWidgets.QCheckBox(self.gridLayoutWidget_5)
        self.checkBox_15.setObjectName("checkBox_15")
        self.gridLayout_6.addWidget(self.checkBox_15, 0, 0, 1, 1)
        self.dial_16 = QtWidgets.QDial(self.gridLayoutWidget_5)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.dial_16.sizePolicy().hasHeightForWidth())
        self.dial_16.setSizePolicy(sizePolicy)
        self.dial_16.setMaximumSize(QtCore.QSize(50, 50))
        self.dial_16.setObjectName("dial_16")
        self.gridLayout_6.addWidget(self.dial_16, 1, 4, 1, 1)
        self.label_43 = QtWidgets.QLabel(self.gridLayoutWidget_5)
        self.label_43.setObjectName("label_43")
        self.gridLayout_6.addWidget(self.label_43, 0, 2, 1, 1)
        self.dial_17 = QtWidgets.QDial(self.gridLayoutWidget_5)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.dial_17.sizePolicy().hasHeightForWidth())
        self.dial_17.setSizePolicy(sizePolicy)
        self.dial_17.setMaximumSize(QtCore.QSize(50, 50))
        self.dial_17.setObjectName("dial_17")
        self.gridLayout_6.addWidget(self.dial_17, 0, 4, 1, 1)
        self.label_44 = QtWidgets.QLabel(self.gridLayoutWidget_5)
        self.label_44.setObjectName("label_44")
        self.gridLayout_6.addWidget(self.label_44, 1, 2, 1, 1)
        self.checkBox_16 = QtWidgets.QCheckBox(self.gridLayoutWidget_5)
        self.checkBox_16.setStyleSheet("font: 11pt \".SF NS Text\";")
        self.checkBox_16.setObjectName("checkBox_16")
        self.gridLayout_6.addWidget(self.checkBox_16, 1, 0, 1, 1)
        self.frame_13 = QtWidgets.QFrame(self.gridLayoutWidget_5)
        self.frame_13.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_13.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_13.setObjectName("frame_13")
        self.verticalLayout_22 = QtWidgets.QVBoxLayout(self.frame_13)
        self.verticalLayout_22.setContentsMargins(6, 0, 0, 0)
        self.verticalLayout_22.setObjectName("verticalLayout_22")
        self.spinBox_13 = QtWidgets.QSpinBox(self.frame_13)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.spinBox_13.sizePolicy().hasHeightForWidth())
        self.spinBox_13.setSizePolicy(sizePolicy)
        self.spinBox_13.setObjectName("spinBox_13")
        self.verticalLayout_22.addWidget(self.spinBox_13)
        self.radioButton_13 = QtWidgets.QRadioButton(self.frame_13)
        self.radioButton_13.setObjectName("radioButton_13")
        self.verticalLayout_22.addWidget(self.radioButton_13)
        self.gridLayout_6.addWidget(self.frame_13, 0, 1, 1, 1)
        self.frame_14 = QtWidgets.QFrame(self.gridLayoutWidget_5)
        self.frame_14.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_14.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_14.setObjectName("frame_14")
        self.verticalLayout_23 = QtWidgets.QVBoxLayout(self.frame_14)
        self.verticalLayout_23.setContentsMargins(6, 0, 0, 0)
        self.verticalLayout_23.setObjectName("verticalLayout_23")
        self.spinBox_14 = QtWidgets.QSpinBox(self.frame_14)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.spinBox_14.sizePolicy().hasHeightForWidth())
        self.spinBox_14.setSizePolicy(sizePolicy)
        self.spinBox_14.setObjectName("spinBox_14")
        self.verticalLayout_23.addWidget(self.spinBox_14)
        self.radioButton_14 = QtWidgets.QRadioButton(self.frame_14)
        self.radioButton_14.setObjectName("radioButton_14")
        self.verticalLayout_23.addWidget(self.radioButton_14)
        self.gridLayout_6.addWidget(self.frame_14, 1, 1, 1, 1)
        self.checkBox_17 = QtWidgets.QCheckBox(self.gridLayoutWidget_5)
        self.checkBox_17.setObjectName("checkBox_17")
        self.gridLayout_6.addWidget(self.checkBox_17, 2, 0, 1, 1)
        self.frame_15 = QtWidgets.QFrame(self.gridLayoutWidget_5)
        self.frame_15.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_15.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_15.setObjectName("frame_15")
        self.verticalLayout_24 = QtWidgets.QVBoxLayout(self.frame_15)
        self.verticalLayout_24.setContentsMargins(6, 0, 0, 0)
        self.verticalLayout_24.setObjectName("verticalLayout_24")
        self.spinBox_15 = QtWidgets.QSpinBox(self.frame_15)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.spinBox_15.sizePolicy().hasHeightForWidth())
        self.spinBox_15.setSizePolicy(sizePolicy)
        self.spinBox_15.setObjectName("spinBox_15")
        self.verticalLayout_24.addWidget(self.spinBox_15)
        self.radioButton_15 = QtWidgets.QRadioButton(self.frame_15)
        self.radioButton_15.setObjectName("radioButton_15")
        self.verticalLayout_24.addWidget(self.radioButton_15)
        self.gridLayout_6.addWidget(self.frame_15, 2, 1, 1, 1)
        self.label_45 = QtWidgets.QLabel(self.gridLayoutWidget_5)
        self.label_45.setObjectName("label_45")
        self.gridLayout_6.addWidget(self.label_45, 2, 2, 1, 1)
        self.label_46 = QtWidgets.QLabel(self.gridLayoutWidget_5)
        self.label_46.setObjectName("label_46")
        self.gridLayout_6.addWidget(self.label_46, 2, 3, 1, 1, QtCore.Qt.AlignHCenter)
        self.dial_18 = QtWidgets.QDial(self.gridLayoutWidget_5)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.dial_18.sizePolicy().hasHeightForWidth())
        self.dial_18.setSizePolicy(sizePolicy)
        self.dial_18.setMaximumSize(QtCore.QSize(50, 50))
        self.dial_18.setObjectName("dial_18")
        self.gridLayout_6.addWidget(self.dial_18, 2, 4, 1, 1)
        self.line_8 = QtWidgets.QFrame(self.groupBox_2)
        self.line_8.setGeometry(QtCore.QRect(50, 570, 291, 20))
        self.line_8.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_8.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_8.setObjectName("line_8")
        self.label_47 = QtWidgets.QLabel(self.groupBox_2)
        self.label_47.setGeometry(QtCore.QRect(30, 770, 91, 31))
        self.label_47.setWordWrap(True)
        self.label_47.setObjectName("label_47")
        self.line_13 = QtWidgets.QFrame(self.groupBox_2)
        self.line_13.setGeometry(QtCore.QRect(460, 570, 291, 20))
        self.line_13.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_13.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_13.setObjectName("line_13")
        self.gridLayoutWidget_9 = QtWidgets.QWidget(self.groupBox_2)
        self.gridLayoutWidget_9.setGeometry(QtCore.QRect(420, 370, 371, 201))
        self.gridLayoutWidget_9.setObjectName("gridLayoutWidget_9")
        self.gridLayout_10 = QtWidgets.QGridLayout(self.gridLayoutWidget_9)
        self.gridLayout_10.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_10.setObjectName("gridLayout_10")
        self.label_72 = QtWidgets.QLabel(self.gridLayoutWidget_9)
        self.label_72.setObjectName("label_72")
        self.gridLayout_10.addWidget(self.label_72, 1, 3, 1, 1, QtCore.Qt.AlignHCenter)
        self.label_73 = QtWidgets.QLabel(self.gridLayoutWidget_9)
        self.label_73.setObjectName("label_73")
        self.gridLayout_10.addWidget(self.label_73, 0, 3, 1, 1, QtCore.Qt.AlignHCenter)
        self.checkBox_28 = QtWidgets.QCheckBox(self.gridLayoutWidget_9)
        self.checkBox_28.setObjectName("checkBox_28")
        self.gridLayout_10.addWidget(self.checkBox_28, 0, 0, 1, 1)
        self.dial_29 = QtWidgets.QDial(self.gridLayoutWidget_9)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.dial_29.sizePolicy().hasHeightForWidth())
        self.dial_29.setSizePolicy(sizePolicy)
        self.dial_29.setMaximumSize(QtCore.QSize(50, 50))
        self.dial_29.setObjectName("dial_29")
        self.gridLayout_10.addWidget(self.dial_29, 1, 4, 1, 1)
        self.label_74 = QtWidgets.QLabel(self.gridLayoutWidget_9)
        self.label_74.setObjectName("label_74")
        self.gridLayout_10.addWidget(self.label_74, 0, 2, 1, 1)
        self.dial_30 = QtWidgets.QDial(self.gridLayoutWidget_9)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.dial_30.sizePolicy().hasHeightForWidth())
        self.dial_30.setSizePolicy(sizePolicy)
        self.dial_30.setMaximumSize(QtCore.QSize(50, 50))
        self.dial_30.setObjectName("dial_30")
        self.gridLayout_10.addWidget(self.dial_30, 0, 4, 1, 1)
        self.label_75 = QtWidgets.QLabel(self.gridLayoutWidget_9)
        self.label_75.setObjectName("label_75")
        self.gridLayout_10.addWidget(self.label_75, 1, 2, 1, 1)
        self.checkBox_29 = QtWidgets.QCheckBox(self.gridLayoutWidget_9)
        self.checkBox_29.setObjectName("checkBox_29")
        self.gridLayout_10.addWidget(self.checkBox_29, 1, 0, 1, 1)
        self.frame_25 = QtWidgets.QFrame(self.gridLayoutWidget_9)
        self.frame_25.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_25.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_25.setObjectName("frame_25")
        self.verticalLayout_34 = QtWidgets.QVBoxLayout(self.frame_25)
        self.verticalLayout_34.setContentsMargins(6, 0, 0, 0)
        self.verticalLayout_34.setObjectName("verticalLayout_34")
        self.spinBox_25 = QtWidgets.QSpinBox(self.frame_25)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.spinBox_25.sizePolicy().hasHeightForWidth())
        self.spinBox_25.setSizePolicy(sizePolicy)
        self.spinBox_25.setObjectName("spinBox_25")
        self.verticalLayout_34.addWidget(self.spinBox_25)
        self.radioButton_25 = QtWidgets.QRadioButton(self.frame_25)
        self.radioButton_25.setObjectName("radioButton_25")
        self.verticalLayout_34.addWidget(self.radioButton_25)
        self.gridLayout_10.addWidget(self.frame_25, 0, 1, 1, 1)
        self.frame_26 = QtWidgets.QFrame(self.gridLayoutWidget_9)
        self.frame_26.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_26.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_26.setObjectName("frame_26")
        self.verticalLayout_35 = QtWidgets.QVBoxLayout(self.frame_26)
        self.verticalLayout_35.setContentsMargins(6, 0, 0, 0)
        self.verticalLayout_35.setObjectName("verticalLayout_35")
        self.spinBox_26 = QtWidgets.QSpinBox(self.frame_26)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.spinBox_26.sizePolicy().hasHeightForWidth())
        self.spinBox_26.setSizePolicy(sizePolicy)
        self.spinBox_26.setObjectName("spinBox_26")
        self.verticalLayout_35.addWidget(self.spinBox_26)
        self.radioButton_26 = QtWidgets.QRadioButton(self.frame_26)
        self.radioButton_26.setObjectName("radioButton_26")
        self.verticalLayout_35.addWidget(self.radioButton_26)
        self.gridLayout_10.addWidget(self.frame_26, 1, 1, 1, 1)
        self.checkBox_30 = QtWidgets.QCheckBox(self.gridLayoutWidget_9)
        self.checkBox_30.setObjectName("checkBox_30")
        self.gridLayout_10.addWidget(self.checkBox_30, 2, 0, 1, 1)
        self.frame_27 = QtWidgets.QFrame(self.gridLayoutWidget_9)
        self.frame_27.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_27.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_27.setObjectName("frame_27")
        self.verticalLayout_36 = QtWidgets.QVBoxLayout(self.frame_27)
        self.verticalLayout_36.setContentsMargins(6, 0, 0, 0)
        self.verticalLayout_36.setObjectName("verticalLayout_36")
        self.spinBox_27 = QtWidgets.QSpinBox(self.frame_27)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.spinBox_27.sizePolicy().hasHeightForWidth())
        self.spinBox_27.setSizePolicy(sizePolicy)
        self.spinBox_27.setObjectName("spinBox_27")
        self.verticalLayout_36.addWidget(self.spinBox_27)
        self.radioButton_27 = QtWidgets.QRadioButton(self.frame_27)
        self.radioButton_27.setObjectName("radioButton_27")
        self.verticalLayout_36.addWidget(self.radioButton_27)
        self.gridLayout_10.addWidget(self.frame_27, 2, 1, 1, 1)
        self.label_76 = QtWidgets.QLabel(self.gridLayoutWidget_9)
        self.label_76.setObjectName("label_76")
        self.gridLayout_10.addWidget(self.label_76, 2, 2, 1, 1)
        self.label_77 = QtWidgets.QLabel(self.gridLayoutWidget_9)
        self.label_77.setObjectName("label_77")
        self.gridLayout_10.addWidget(self.label_77, 2, 3, 1, 1, QtCore.Qt.AlignHCenter)
        self.dial_31 = QtWidgets.QDial(self.gridLayoutWidget_9)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.dial_31.sizePolicy().hasHeightForWidth())
        self.dial_31.setSizePolicy(sizePolicy)
        self.dial_31.setMaximumSize(QtCore.QSize(50, 50))
        self.dial_31.setObjectName("dial_31")
        self.gridLayout_10.addWidget(self.dial_31, 2, 4, 1, 1)
        self.gridLayoutWidget_10 = QtWidgets.QWidget(self.groupBox_2)
        self.gridLayoutWidget_10.setGeometry(QtCore.QRect(420, 150, 371, 201))
        self.gridLayoutWidget_10.setObjectName("gridLayoutWidget_10")
        self.gridLayout_11 = QtWidgets.QGridLayout(self.gridLayoutWidget_10)
        self.gridLayout_11.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_11.setObjectName("gridLayout_11")
        self.label_78 = QtWidgets.QLabel(self.gridLayoutWidget_10)
        self.label_78.setObjectName("label_78")
        self.gridLayout_11.addWidget(self.label_78, 1, 3, 1, 1, QtCore.Qt.AlignHCenter)
        self.label_79 = QtWidgets.QLabel(self.gridLayoutWidget_10)
        self.label_79.setObjectName("label_79")
        self.gridLayout_11.addWidget(self.label_79, 0, 3, 1, 1, QtCore.Qt.AlignHCenter)
        self.checkBox_31 = QtWidgets.QCheckBox(self.gridLayoutWidget_10)
        self.checkBox_31.setObjectName("checkBox_31")
        self.gridLayout_11.addWidget(self.checkBox_31, 0, 0, 1, 1)
        self.dial_32 = QtWidgets.QDial(self.gridLayoutWidget_10)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.dial_32.sizePolicy().hasHeightForWidth())
        self.dial_32.setSizePolicy(sizePolicy)
        self.dial_32.setMaximumSize(QtCore.QSize(50, 50))
        self.dial_32.setObjectName("dial_32")
        self.gridLayout_11.addWidget(self.dial_32, 1, 4, 1, 1)
        self.label_80 = QtWidgets.QLabel(self.gridLayoutWidget_10)
        self.label_80.setObjectName("label_80")
        self.gridLayout_11.addWidget(self.label_80, 0, 2, 1, 1)
        self.dial_33 = QtWidgets.QDial(self.gridLayoutWidget_10)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.dial_33.sizePolicy().hasHeightForWidth())
        self.dial_33.setSizePolicy(sizePolicy)
        self.dial_33.setMaximumSize(QtCore.QSize(50, 50))
        self.dial_33.setObjectName("dial_33")
        self.gridLayout_11.addWidget(self.dial_33, 0, 4, 1, 1)
        self.label_81 = QtWidgets.QLabel(self.gridLayoutWidget_10)
        self.label_81.setObjectName("label_81")
        self.gridLayout_11.addWidget(self.label_81, 1, 2, 1, 1)
        self.checkBox_32 = QtWidgets.QCheckBox(self.gridLayoutWidget_10)
        self.checkBox_32.setObjectName("checkBox_32")
        self.gridLayout_11.addWidget(self.checkBox_32, 1, 0, 1, 1)
        self.frame_28 = QtWidgets.QFrame(self.gridLayoutWidget_10)
        self.frame_28.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_28.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_28.setObjectName("frame_28")
        self.verticalLayout_37 = QtWidgets.QVBoxLayout(self.frame_28)
        self.verticalLayout_37.setContentsMargins(6, 0, 0, 0)
        self.verticalLayout_37.setObjectName("verticalLayout_37")
        self.spinBox_28 = QtWidgets.QSpinBox(self.frame_28)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.spinBox_28.sizePolicy().hasHeightForWidth())
        self.spinBox_28.setSizePolicy(sizePolicy)
        self.spinBox_28.setObjectName("spinBox_28")
        self.verticalLayout_37.addWidget(self.spinBox_28)
        self.radioButton_28 = QtWidgets.QRadioButton(self.frame_28)
        self.radioButton_28.setObjectName("radioButton_28")
        self.verticalLayout_37.addWidget(self.radioButton_28)
        self.gridLayout_11.addWidget(self.frame_28, 0, 1, 1, 1)
        self.frame_29 = QtWidgets.QFrame(self.gridLayoutWidget_10)
        self.frame_29.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_29.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_29.setObjectName("frame_29")
        self.verticalLayout_38 = QtWidgets.QVBoxLayout(self.frame_29)
        self.verticalLayout_38.setContentsMargins(6, 0, 0, 0)
        self.verticalLayout_38.setObjectName("verticalLayout_38")
        self.spinBox_29 = QtWidgets.QSpinBox(self.frame_29)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.spinBox_29.sizePolicy().hasHeightForWidth())
        self.spinBox_29.setSizePolicy(sizePolicy)
        self.spinBox_29.setObjectName("spinBox_29")
        self.verticalLayout_38.addWidget(self.spinBox_29)
        self.radioButton_29 = QtWidgets.QRadioButton(self.frame_29)
        self.radioButton_29.setObjectName("radioButton_29")
        self.verticalLayout_38.addWidget(self.radioButton_29)
        self.gridLayout_11.addWidget(self.frame_29, 1, 1, 1, 1)
        self.checkBox_33 = QtWidgets.QCheckBox(self.gridLayoutWidget_10)
        self.checkBox_33.setObjectName("checkBox_33")
        self.gridLayout_11.addWidget(self.checkBox_33, 2, 0, 1, 1)
        self.frame_30 = QtWidgets.QFrame(self.gridLayoutWidget_10)
        self.frame_30.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_30.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_30.setObjectName("frame_30")
        self.verticalLayout_39 = QtWidgets.QVBoxLayout(self.frame_30)
        self.verticalLayout_39.setContentsMargins(6, 0, 0, 0)
        self.verticalLayout_39.setObjectName("verticalLayout_39")
        self.spinBox_30 = QtWidgets.QSpinBox(self.frame_30)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.spinBox_30.sizePolicy().hasHeightForWidth())
        self.spinBox_30.setSizePolicy(sizePolicy)
        self.spinBox_30.setObjectName("spinBox_30")
        self.verticalLayout_39.addWidget(self.spinBox_30)
        self.radioButton_30 = QtWidgets.QRadioButton(self.frame_30)
        self.radioButton_30.setObjectName("radioButton_30")
        self.verticalLayout_39.addWidget(self.radioButton_30)
        self.gridLayout_11.addWidget(self.frame_30, 2, 1, 1, 1)
        self.label_82 = QtWidgets.QLabel(self.gridLayoutWidget_10)
        self.label_82.setObjectName("label_82")
        self.gridLayout_11.addWidget(self.label_82, 2, 2, 1, 1)
        self.label_83 = QtWidgets.QLabel(self.gridLayoutWidget_10)
        self.label_83.setObjectName("label_83")
        self.gridLayout_11.addWidget(self.label_83, 2, 3, 1, 1, QtCore.Qt.AlignHCenter)
        self.dial_34 = QtWidgets.QDial(self.gridLayoutWidget_10)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.dial_34.sizePolicy().hasHeightForWidth())
        self.dial_34.setSizePolicy(sizePolicy)
        self.dial_34.setMaximumSize(QtCore.QSize(50, 50))
        self.dial_34.setObjectName("dial_34")
        self.gridLayout_11.addWidget(self.dial_34, 2, 4, 1, 1)
        self.line_14 = QtWidgets.QFrame(self.groupBox_2)
        self.line_14.setGeometry(QtCore.QRect(460, 350, 291, 20))
        self.line_14.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_14.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_14.setObjectName("line_14")
        self.label_84 = QtWidgets.QLabel(self.groupBox_2)
        self.label_84.setGeometry(QtCore.QRect(440, 770, 91, 31))
        self.label_84.setWordWrap(True)
        self.label_84.setObjectName("label_84")
        self.gridLayoutWidget_11 = QtWidgets.QWidget(self.groupBox_2)
        self.gridLayoutWidget_11.setGeometry(QtCore.QRect(420, 590, 371, 201))
        self.gridLayoutWidget_11.setObjectName("gridLayoutWidget_11")
        self.gridLayout_12 = QtWidgets.QGridLayout(self.gridLayoutWidget_11)
        self.gridLayout_12.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_12.setObjectName("gridLayout_12")
        self.label_85 = QtWidgets.QLabel(self.gridLayoutWidget_11)
        self.label_85.setObjectName("label_85")
        self.gridLayout_12.addWidget(self.label_85, 1, 3, 1, 1, QtCore.Qt.AlignHCenter)
        self.label_86 = QtWidgets.QLabel(self.gridLayoutWidget_11)
        self.label_86.setObjectName("label_86")
        self.gridLayout_12.addWidget(self.label_86, 0, 3, 1, 1, QtCore.Qt.AlignHCenter)
        self.checkBox_34 = QtWidgets.QCheckBox(self.gridLayoutWidget_11)
        self.checkBox_34.setObjectName("checkBox_34")
        self.gridLayout_12.addWidget(self.checkBox_34, 0, 0, 1, 1)
        self.dial_35 = QtWidgets.QDial(self.gridLayoutWidget_11)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.dial_35.sizePolicy().hasHeightForWidth())
        self.dial_35.setSizePolicy(sizePolicy)
        self.dial_35.setMaximumSize(QtCore.QSize(50, 50))
        self.dial_35.setObjectName("dial_35")
        self.gridLayout_12.addWidget(self.dial_35, 1, 4, 1, 1)
        self.label_87 = QtWidgets.QLabel(self.gridLayoutWidget_11)
        self.label_87.setObjectName("label_87")
        self.gridLayout_12.addWidget(self.label_87, 0, 2, 1, 1)
        self.dial_36 = QtWidgets.QDial(self.gridLayoutWidget_11)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.dial_36.sizePolicy().hasHeightForWidth())
        self.dial_36.setSizePolicy(sizePolicy)
        self.dial_36.setMaximumSize(QtCore.QSize(50, 50))
        self.dial_36.setObjectName("dial_36")
        self.gridLayout_12.addWidget(self.dial_36, 0, 4, 1, 1)
        self.label_88 = QtWidgets.QLabel(self.gridLayoutWidget_11)
        self.label_88.setObjectName("label_88")
        self.gridLayout_12.addWidget(self.label_88, 1, 2, 1, 1)
        self.checkBox_35 = QtWidgets.QCheckBox(self.gridLayoutWidget_11)
        self.checkBox_35.setStyleSheet("font: 11pt \".SF NS Text\";")
        self.checkBox_35.setObjectName("checkBox_35")
        self.gridLayout_12.addWidget(self.checkBox_35, 1, 0, 1, 1)
        self.frame_31 = QtWidgets.QFrame(self.gridLayoutWidget_11)
        self.frame_31.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_31.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_31.setObjectName("frame_31")
        self.verticalLayout_40 = QtWidgets.QVBoxLayout(self.frame_31)
        self.verticalLayout_40.setContentsMargins(6, 0, 0, 0)
        self.verticalLayout_40.setObjectName("verticalLayout_40")
        self.spinBox_31 = QtWidgets.QSpinBox(self.frame_31)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.spinBox_31.sizePolicy().hasHeightForWidth())
        self.spinBox_31.setSizePolicy(sizePolicy)
        self.spinBox_31.setObjectName("spinBox_31")
        self.verticalLayout_40.addWidget(self.spinBox_31)
        self.radioButton_31 = QtWidgets.QRadioButton(self.frame_31)
        self.radioButton_31.setObjectName("radioButton_31")
        self.verticalLayout_40.addWidget(self.radioButton_31)
        self.gridLayout_12.addWidget(self.frame_31, 0, 1, 1, 1)
        self.frame_32 = QtWidgets.QFrame(self.gridLayoutWidget_11)
        self.frame_32.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_32.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_32.setObjectName("frame_32")
        self.verticalLayout_41 = QtWidgets.QVBoxLayout(self.frame_32)
        self.verticalLayout_41.setContentsMargins(6, 0, 0, 0)
        self.verticalLayout_41.setObjectName("verticalLayout_41")
        self.spinBox_32 = QtWidgets.QSpinBox(self.frame_32)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.spinBox_32.sizePolicy().hasHeightForWidth())
        self.spinBox_32.setSizePolicy(sizePolicy)
        self.spinBox_32.setObjectName("spinBox_32")
        self.verticalLayout_41.addWidget(self.spinBox_32)
        self.radioButton_32 = QtWidgets.QRadioButton(self.frame_32)
        self.radioButton_32.setObjectName("radioButton_32")
        self.verticalLayout_41.addWidget(self.radioButton_32)
        self.gridLayout_12.addWidget(self.frame_32, 1, 1, 1, 1)
        self.checkBox_36 = QtWidgets.QCheckBox(self.gridLayoutWidget_11)
        self.checkBox_36.setObjectName("checkBox_36")
        self.gridLayout_12.addWidget(self.checkBox_36, 2, 0, 1, 1)
        self.frame_33 = QtWidgets.QFrame(self.gridLayoutWidget_11)
        self.frame_33.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_33.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_33.setObjectName("frame_33")
        self.verticalLayout_42 = QtWidgets.QVBoxLayout(self.frame_33)
        self.verticalLayout_42.setContentsMargins(6, 0, 0, 0)
        self.verticalLayout_42.setObjectName("verticalLayout_42")
        self.spinBox_33 = QtWidgets.QSpinBox(self.frame_33)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.spinBox_33.sizePolicy().hasHeightForWidth())
        self.spinBox_33.setSizePolicy(sizePolicy)
        self.spinBox_33.setObjectName("spinBox_33")
        self.verticalLayout_42.addWidget(self.spinBox_33)
        self.radioButton_33 = QtWidgets.QRadioButton(self.frame_33)
        self.radioButton_33.setObjectName("radioButton_33")
        self.verticalLayout_42.addWidget(self.radioButton_33)
        self.gridLayout_12.addWidget(self.frame_33, 2, 1, 1, 1)
        self.label_89 = QtWidgets.QLabel(self.gridLayoutWidget_11)
        self.label_89.setObjectName("label_89")
        self.gridLayout_12.addWidget(self.label_89, 2, 2, 1, 1)
        self.label_90 = QtWidgets.QLabel(self.gridLayoutWidget_11)
        self.label_90.setObjectName("label_90")
        self.gridLayout_12.addWidget(self.label_90, 2, 3, 1, 1, QtCore.Qt.AlignHCenter)
        self.dial_37 = QtWidgets.QDial(self.gridLayoutWidget_11)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.dial_37.sizePolicy().hasHeightForWidth())
        self.dial_37.setSizePolicy(sizePolicy)
        self.dial_37.setMaximumSize(QtCore.QSize(50, 50))
        self.dial_37.setObjectName("dial_37")
        self.gridLayout_12.addWidget(self.dial_37, 2, 4, 1, 1)
        self.label_91 = QtWidgets.QLabel(self.groupBox_2)
        self.label_91.setGeometry(QtCore.QRect(20, 810, 701, 31))
        self.label_91.setWordWrap(True)
        self.label_91.setObjectName("label_91")
        self.layoutWidget = QtWidgets.QWidget(self.groupBox_2)
        self.layoutWidget.setGeometry(QtCore.QRect(10, 60, 291, 57))
        self.layoutWidget.setObjectName("layoutWidget")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.layoutWidget)
        self.horizontalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.checkBox_7 = QtWidgets.QCheckBox(self.layoutWidget)
        self.checkBox_7.setObjectName("checkBox_7")
        self.horizontalLayout_5.addWidget(self.checkBox_7)
        self.label_22 = QtWidgets.QLabel(self.layoutWidget)
        self.label_22.setObjectName("label_22")
        self.horizontalLayout_5.addWidget(self.label_22)
        self.label_23 = QtWidgets.QLabel(self.layoutWidget)
        self.label_23.setObjectName("label_23")
        self.horizontalLayout_5.addWidget(self.label_23, 0, QtCore.Qt.AlignHCenter)
        self.dial_8 = QtWidgets.QDial(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.dial_8.sizePolicy().hasHeightForWidth())
        self.dial_8.setSizePolicy(sizePolicy)
        self.dial_8.setMaximumSize(QtCore.QSize(50, 50))
        self.dial_8.setObjectName("dial_8")
        self.horizontalLayout_5.addWidget(self.dial_8)
        self.tabWidget.addTab(self.Influencers, "")
        self.verticalLayout_2.addWidget(self.tabWidget)
        principale_IHM.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(principale_IHM)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 893, 22))
        self.menubar.setObjectName("menubar")
        self.menuFiles = QtWidgets.QMenu(self.menubar)
        self.menuFiles.setObjectName("menuFiles")
        principale_IHM.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(principale_IHM)
        self.statusbar.setObjectName("statusbar")
        principale_IHM.setStatusBar(self.statusbar)
        self.actionQuit = QtWidgets.QAction(principale_IHM)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("../iceberg.jpeg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionQuit.setIcon(icon)
        self.actionQuit.setObjectName("actionQuit")
        self.menuFiles.addAction(self.actionQuit)
        self.menuFiles.addSeparator()
        self.menubar.addAction(self.menuFiles.menuAction())

        self.retranslateUi(principale_IHM)
        self.tabWidget.setCurrentIndex(0)
        self.actionQuit.triggered.connect(principale_IHM.close)
        self.dial_8.valueChanged['int'].connect(self.label_23.setNum)
        self.dial_2.valueChanged['int'].connect(self.label_10.setNum)
        self.dial_9.valueChanged['int'].connect(self.label_26.setNum)
        self.dial_3.valueChanged['int'].connect(self.label_13.setNum)
        self.dial_4.valueChanged['int'].connect(self.label_15.setNum)
        self.dial_6.valueChanged['int'].connect(self.label_17.setNum)
        self.dial_5.valueChanged['int'].connect(self.label_16.setNum)
        self.dial_7.valueChanged['int'].connect(self.label_21.setNum)
        self.dial_17.valueChanged['int'].connect(self.label_42.setNum)
        self.dial_16.valueChanged['int'].connect(self.label_41.setNum)
        self.dial_18.valueChanged['int'].connect(self.label_46.setNum)
        self.dial_33.valueChanged['int'].connect(self.label_79.setNum)
        self.dial_32.valueChanged['int'].connect(self.label_78.setNum)
        self.dial_34.valueChanged['int'].connect(self.label_83.setNum)
        self.dial_30.valueChanged['int'].connect(self.label_73.setNum)
        self.dial_29.valueChanged['int'].connect(self.label_72.setNum)
        self.dial_31.valueChanged['int'].connect(self.label_77.setNum)
        self.dial_36.valueChanged['int'].connect(self.label_86.setNum)
        self.dial_35.valueChanged['int'].connect(self.label_85.setNum)
        self.dial_37.valueChanged['int'].connect(self.label_90.setNum)
        QtCore.QMetaObject.connectSlotsByName(principale_IHM)

    def retranslateUi(self, principale_IHM):
        _translate = QtCore.QCoreApplication.translate
        principale_IHM.setWindowTitle(_translate("principale_IHM", "influencer_forge"))
        item = self.tableWidget.verticalHeaderItem(0)
        item.setText(_translate("principale_IHM", "Nouvelle ligne"))
        item = self.tableWidget.verticalHeaderItem(1)
        item.setText(_translate("principale_IHM", "ergw"))
        item = self.tableWidget.verticalHeaderItem(2)
        item.setText(_translate("principale_IHM", "fgfw"))
        item = self.tableWidget.verticalHeaderItem(3)
        item.setText(_translate("principale_IHM", "wfvf"))
        item = self.tableWidget.verticalHeaderItem(4)
        item.setText(_translate("principale_IHM", "fvs"))
        item = self.tableWidget.verticalHeaderItem(5)
        item.setText(_translate("principale_IHM", "Nouvelle ligne"))
        item = self.tableWidget.verticalHeaderItem(6)
        item.setText(_translate("principale_IHM", "dsfvf"))
        item = self.tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("principale_IHM", "concept"))
        item = self.tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("principale_IHM", "score"))
        self.groupBox.setTitle(_translate("principale_IHM", "Video under scrutiny"))
        self.label__txt_file.setText(_translate("principale_IHM", "txt file:"))
        self.label__txt_file_2.setText(_translate("principale_IHM", "Available videos:"))
        self.label.setText(_translate("principale_IHM", "TextLabel"))
        self.pushButton_4.setText(_translate("principale_IHM", "Commit"))
        self.comboBox.setItemText(0, _translate("principale_IHM", "hola"))
        self.comboBox.setItemText(1, _translate("principale_IHM", "buenos dias"))
        self.treeWidget.headerItem().setText(0, _translate("principale_IHM", "course architecture"))
        __sortingEnabled = self.treeWidget.isSortingEnabled()
        self.treeWidget.setSortingEnabled(False)
        self.treeWidget.topLevelItem(0).setText(0, _translate("principale_IHM", "course_name"))
        self.treeWidget.topLevelItem(0).child(0).setText(0, _translate("principale_IHM", "chap1"))
        self.treeWidget.topLevelItem(0).child(0).child(0).setText(0, _translate("principale_IHM", "seq1"))
        self.treeWidget.topLevelItem(0).child(0).child(0).child(0).setText(0, _translate("principale_IHM", "vert1"))
        self.treeWidget.setSortingEnabled(__sortingEnabled)
        self.pushButton.setText(_translate("principale_IHM", "Score"))
        self.pushButton_2.setText(_translate("principale_IHM", "Get concepts"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("principale_IHM", "Concepts"))
        self.label_5.setText(_translate("principale_IHM", "Influencer"))
        self.label_8.setText(_translate("principale_IHM", "is influenced by:"))
        item = self.tableWidget_2.verticalHeaderItem(0)
        item.setText(_translate("principale_IHM", "dzcxc"))
        item = self.tableWidget_2.verticalHeaderItem(1)
        item.setText(_translate("principale_IHM", "afda"))
        item = self.tableWidget_2.verticalHeaderItem(2)
        item.setText(_translate("principale_IHM", "Nouvelle ligne"))
        item = self.tableWidget_2.verticalHeaderItem(3)
        item.setText(_translate("principale_IHM", "asdf"))
        item = self.tableWidget_2.verticalHeaderItem(4)
        item.setText(_translate("principale_IHM", "sdf"))
        item = self.tableWidget_2.verticalHeaderItem(5)
        item.setText(_translate("principale_IHM", "sdf"))
        item = self.tableWidget_2.verticalHeaderItem(6)
        item.setText(_translate("principale_IHM", "sdf"))
        item = self.tableWidget_2.verticalHeaderItem(7)
        item.setText(_translate("principale_IHM", "sdf"))
        item = self.tableWidget_2.verticalHeaderItem(8)
        item.setText(_translate("principale_IHM", "asdfadsf"))
        item = self.tableWidget_2.horizontalHeaderItem(0)
        item.setText(_translate("principale_IHM", "Influencer"))
        item = self.tableWidget_2.horizontalHeaderItem(1)
        item.setText(_translate("principale_IHM", "Resemblance"))
        __sortingEnabled = self.tableWidget_2.isSortingEnabled()
        self.tableWidget_2.setSortingEnabled(False)
        item = self.tableWidget_2.item(0, 0)
        item.setText(_translate("principale_IHM", "xcxc"))
        item = self.tableWidget_2.item(0, 1)
        item.setText(_translate("principale_IHM", "xcx"))
        self.tableWidget_2.setSortingEnabled(__sortingEnabled)
        self.groupBox_4.setTitle(_translate("principale_IHM", "Add influencer "))
        self.label_24.setText(_translate("principale_IHM", "Influencer under scrutiny should also be influenced by:"))
        self.pushButton_3.setText(_translate("principale_IHM", "Add"))
        self.label_25.setText(_translate("principale_IHM", "with  percentage"))
        self.label_26.setText(_translate("principale_IHM", "0"))
        self.pushButton_5.setText(_translate("principale_IHM", "Generate id_map"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("principale_IHM", "Individual parameters"))
        self.groupBox_2.setTitle(_translate("principale_IHM", "Recursion built influencers (RBIs)"))
        self.label_4.setText(_translate("principale_IHM", "RBIs will be influenced by:"))
        self.label_12.setText(_translate("principale_IHM", "<html><head/><body><p><span style=\" font-size:10pt;\">The higher the resemblance percentage, the more precise (i.e. the less likely to pass trial)</span></p></body></html>"))
        self.label_6.setText(_translate("principale_IHM", "<html><head/><body><p><span style=\" font-weight:600;\">Left</span></p></body></html>"))
        self.label_7.setText(_translate("principale_IHM", "<html><head/><body><p><span style=\" font-weight:600;\">Right</span></p></body></html>"))
        self.label_13.setText(_translate("principale_IHM", "0"))
        self.label_10.setText(_translate("principale_IHM", "0"))
        self.checkBox.setText(_translate("principale_IHM", "Brothers"))
        self.label_9.setText(_translate("principale_IHM", "with  percentage"))
        self.label_11.setText(_translate("principale_IHM", "with  percentage"))
        self.checkBox_2.setText(_translate("principale_IHM", "Fathers"))
        self.radioButton.setText(_translate("principale_IHM", "all"))
        self.radioButton_2.setText(_translate("principale_IHM", "all"))
        self.checkBox_3.setText(_translate("principale_IHM", "Grandfathers"))
        self.radioButton_3.setText(_translate("principale_IHM", "all"))
        self.label_14.setText(_translate("principale_IHM", "with  percentage"))
        self.label_15.setText(_translate("principale_IHM", "0"))
        self.label_16.setText(_translate("principale_IHM", "0"))
        self.label_17.setText(_translate("principale_IHM", "0"))
        self.checkBox_4.setText(_translate("principale_IHM", "Cousins"))
        self.label_18.setText(_translate("principale_IHM", "with  percentage"))
        self.label_19.setText(_translate("principale_IHM", "with  percentage"))
        self.checkBox_5.setText(_translate("principale_IHM", "Uncles"))
        self.radioButton_4.setText(_translate("principale_IHM", "all"))
        self.radioButton_5.setText(_translate("principale_IHM", "all"))
        self.checkBox_6.setText(_translate("principale_IHM", "Granduncles"))
        self.radioButton_6.setText(_translate("principale_IHM", "all"))
        self.label_20.setText(_translate("principale_IHM", "with  percentage"))
        self.label_21.setText(_translate("principale_IHM", "0"))
        self.label_41.setText(_translate("principale_IHM", "0"))
        self.label_42.setText(_translate("principale_IHM", "0"))
        self.checkBox_15.setText(_translate("principale_IHM", "Children"))
        self.label_43.setText(_translate("principale_IHM", "with  percentage"))
        self.label_44.setText(_translate("principale_IHM", "with  percentage"))
        self.checkBox_16.setText(_translate("principale_IHM", "Grandchildren"))
        self.radioButton_13.setText(_translate("principale_IHM", "all"))
        self.radioButton_14.setText(_translate("principale_IHM", "all"))
        self.checkBox_17.setText(_translate("principale_IHM", "Nephews"))
        self.radioButton_15.setText(_translate("principale_IHM", "all"))
        self.label_45.setText(_translate("principale_IHM", "with  percentage"))
        self.label_46.setText(_translate("principale_IHM", "0"))
        self.label_47.setText(_translate("principale_IHM", "<html><head/><body><p><span style=\" font-size:10pt;\">(one generation lower)</span></p></body></html>"))
        self.label_72.setText(_translate("principale_IHM", "0"))
        self.label_73.setText(_translate("principale_IHM", "0"))
        self.checkBox_28.setText(_translate("principale_IHM", "Cousins"))
        self.label_74.setText(_translate("principale_IHM", "with  percentage"))
        self.label_75.setText(_translate("principale_IHM", "with  percentage"))
        self.checkBox_29.setText(_translate("principale_IHM", "Uncles"))
        self.radioButton_25.setText(_translate("principale_IHM", "all"))
        self.radioButton_26.setText(_translate("principale_IHM", "all"))
        self.checkBox_30.setText(_translate("principale_IHM", "Granduncles"))
        self.radioButton_27.setText(_translate("principale_IHM", "all"))
        self.label_76.setText(_translate("principale_IHM", "with  percentage"))
        self.label_77.setText(_translate("principale_IHM", "0"))
        self.label_78.setText(_translate("principale_IHM", "0"))
        self.label_79.setText(_translate("principale_IHM", "0"))
        self.checkBox_31.setText(_translate("principale_IHM", "Brothers"))
        self.label_80.setText(_translate("principale_IHM", "with  percentage"))
        self.label_81.setText(_translate("principale_IHM", "with  percentage"))
        self.checkBox_32.setText(_translate("principale_IHM", "Fathers"))
        self.radioButton_28.setText(_translate("principale_IHM", "all"))
        self.radioButton_29.setText(_translate("principale_IHM", "all"))
        self.checkBox_33.setText(_translate("principale_IHM", "Grandfathers"))
        self.radioButton_30.setText(_translate("principale_IHM", "all"))
        self.label_82.setText(_translate("principale_IHM", "with  percentage"))
        self.label_83.setText(_translate("principale_IHM", "0"))
        self.label_84.setText(_translate("principale_IHM", "<html><head/><body><p><span style=\" font-size:10pt;\">(one generation lower)</span></p></body></html>"))
        self.label_85.setText(_translate("principale_IHM", "0"))
        self.label_86.setText(_translate("principale_IHM", "0"))
        self.checkBox_34.setText(_translate("principale_IHM", "Children"))
        self.label_87.setText(_translate("principale_IHM", "with  percentage"))
        self.label_88.setText(_translate("principale_IHM", "with  percentage"))
        self.checkBox_35.setText(_translate("principale_IHM", "Grandchildren"))
        self.radioButton_31.setText(_translate("principale_IHM", "all"))
        self.radioButton_32.setText(_translate("principale_IHM", "all"))
        self.checkBox_36.setText(_translate("principale_IHM", "Nephews"))
        self.radioButton_33.setText(_translate("principale_IHM", "all"))
        self.label_89.setText(_translate("principale_IHM", "with  percentage"))
        self.label_90.setText(_translate("principale_IHM", "0"))
        self.label_91.setText(_translate("principale_IHM", "<html><head/><body><p>If requested parents are None during recursion, corresponding influencer will not be made.</p></body></html>"))
        self.checkBox_7.setText(_translate("principale_IHM", "Course name"))
        self.label_22.setText(_translate("principale_IHM", "with  percentage"))
        self.label_23.setText(_translate("principale_IHM", "0"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.Influencers), _translate("principale_IHM", "Recursion parameters"))
        self.menuFiles.setTitle(_translate("principale_IHM", "Files"))
        self.actionQuit.setText(_translate("principale_IHM", "Quit"))
        self.actionQuit.setShortcut(_translate("principale_IHM", "Meta+Q"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    principale_IHM = QtWidgets.QMainWindow()
    ui = Ui_principale_IHM()
    ui.setupUi(principale_IHM)
    principale_IHM.show()
    sys.exit(app.exec_())

